# Generated by Django 4.0.5 on 2022-06-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='topic_link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.topics', verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
